// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv tsx
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  // 👇 FIX: 'seed' must be an object with a 'command' property
  seed: {
    command: 'tsx prisma/seed.ts',
  },
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});